// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200403165900_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Gender = "Male",
                            Name = "Alfie",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 6,
                            Gender = "Female",
                            Name = "Cheetah",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            Gender = "Female",
                            Name = "Spike",
                            Type = "Ferret"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 1,
                            Gender = "Male",
                            Name = "Mars",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 2,
                            Gender = "Female",
                            Name = "Leila",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 1,
                            Gender = "Male",
                            Name = "Lenny",
                            Type = "Guinea Pig"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
